### ISSUE TITLE
Not able to run camkes-vm-linux on the AMD platform

### ISSUE THREAD

**Issue by chenyangyy** [seL4/sel4-tutorials#96]
According to [tutorials](https://docs.sel4.systems/Tutorials/camkes-vm-linux.html#:~:text=sudo%20./simulate%20%2D%2Dmachine%20q35%2Caccel%3Dkvm%2Ckernel%2Dirqchip%3Dsplit%20%2D%2Dmem%2Dsize%202G%20%2D%2Dextra%2Dcpu%2Dopts%20%22%2Bvmx%22%20%2D%2Dextra%2Dqemu%2Dargs%3D%22%2Denable%2Dkvm%20%2Ddevice%20intel%2Diommu%2Cintremap%3Doff%20%2Dnet%20nic%2Cmodel%3De1000%20%2Dnet%20tap%2Cscript%3Dno%2Cifname%3Dtap0%22), how can I simulate on the AMD platform?

**Comment by axel-h** [comment]
Could you be more specific about this, what environment are you using and what error do you get?
